# docker-compose.yml
version: "2.2"
services:
  db:
    build: ./backend/banco-de-dados/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d alumni"]
      interval: 5s
      timeout: 5s
      retries: 10

  node:
    build: ./backend/api/
    container_name: node
    command: node index.js
    ports: 
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy