# docker-compose.yml
version: "2.2"
services:
  # app :
  #   build: ./app/
  #   ports:
  #     - "80:80"
  #   depends_on: 
  #     db:
  #       condition: service_healthy
  db:
    build: ./backend/banco-de-dados/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d alumni"]
      interval: 5s
      timeout: 5s
      retries: 10
